BOS = "_BOS_"
EOS = "_EOS_"
PAD = "_PAD_"
SPECIAL_VOCABULARY_SOURCE = {EOS: 0, PAD: 1}
SPECIAL_VOCABULARY_TARGET = {BOS: 0, PAD: 1}

SOURCE_VOCAB_FILE_NAME = "vocab.source.json.gz"
TARGET_VOCAB_FILE_NAME = "vocab.target.json.gz"